export const CHANNELS = Object.freeze({
  APP_INFO: 'hs:v1:app:info',
  WORKSPACE_INFO: 'hs:v1:workspace:info',
  SESSION_LIST: 'hs:v1:session:list',
  SESSION_CREATE: 'hs:v1:session:create',
  TIMELINE_GET: 'hs:v1:timeline:get',
  INFERENCE_RUN: 'hs:v1:inference:run',
  COMPARE_RUN: 'hs:v1:compare:run',
  IMPORT_HAR: 'hs:v1:import:har',
  IMPORT_PROCMON: 'hs:v1:import:procmon',
  IMPORT_JSONL: 'hs:v1:import:jsonl',
  LAUNCH_RUN: 'hs:v1:launch:run',
  EXPORT_RUN: 'hs:v1:export:run',
  COLLECTOR_LIST: 'hs:v1:collector:list',
  COLLECTOR_DESCRIBE: 'hs:v1:collector:describe',
  COLLECTOR_START: 'hs:v1:collector:start',
  COLLECTOR_STOP: 'hs:v1:collector:stop',
  COLLECTOR_STATUS: 'hs:v1:collector:status',
  DIALOG_PICK_DIRECTORY: 'hs:v1:dialog:pick-directory',
  DIALOG_PICK_FILE: 'hs:v1:dialog:pick-file'
});
